---
slug: lectures_on_astroX_problems
filename: lectures_on_astroX_problems
title: Title of the Book
subtitle: Change me
description: Change me.
author: Author Name
copyright: 2017
uuid: 0c10575a-3e41-446c-bf58-fae3befc5363
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
